---
Parameters:
  Token:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "github"
    Description: Github token

Resources:
  TomcatServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0cff7528ff583bf9a
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ServerSG
      Tags:
        - Key: "Name"
          Value: "s3878480_assignment1"
      KeyName: !Ref TomcatServerKey
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            curl "https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz" --output /opt/maven.tar.gz
            cd /opt
            tar -xvzf /opt/maven.tar.gz
            curl "https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.22/bin/apache-tomcat-10.0.22.tar.gz" --output /opt/tomcat.tar.gz
            tar -xvzf /opt/tomcat.tar.gz
            mv apache-maven-3.8.6 maven
            mv apache-tomcat-10.0.22 tomcat
            sudo su -   
            sudo amazon-linux-extras install -y java-openjdk11
            sudo yum install -y git
            M2=/opt/maven
            M2_HOME=/opt/maven/bin
            JAVA_HOME=$(find /usr/lib -name java-11*)
            export PATH=$PATH:$HOME/bin:$JAVA_HOME:$M2:$M2_HOME
            cd /
            git clone 'https://rider3458:${Token}@github.com/rider3458/COSC2767_Assignment1_BashScript_AWS_s3878480.git'
            cd COSC2767_Assignment1_BashScript_AWS_s3878480/personalWebsite
            mvn package
            cp target/personalWebsite.war /opt/tomcat/webapps
            /opt/tomcat/bin/startup.sh

  ServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and port 8080 for Tomcat
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 8080
          IpProtocol: tcp
          ToPort: 8080

  TomcatServerKey:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: "s3878480_key"

Outputs:
  Website:
    Description: Server Public IP
    Value: !Join
      - ''
      - - !GetAtt TomcatServer.PublicIp
        - ":8080/personalWebsite"